//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneKonta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaneKonta()
        {
            this.GrywMojejBiblioteces = new HashSet<GrywMojejBibliotece>();
            this.Friends = new HashSet<Friend>();
            this.HistoriaZakupows = new HashSet<HistoriaZakupow>();
        }
    
        public int Id { get; set; }
        public string NazwaUżytkownika { get; set; }
        public string HasloUzytkownika { get; set; }
        public string EmailAdress { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Płeć { get; set; }
        public string Hobby { get; set; }
        public string Narodowosc { get; set; }
        public string Miejscowosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrywMojejBibliotece> GrywMojejBiblioteces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaZakupow> HistoriaZakupows { get; set; }
    }
}
