//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane
    {
        public int Id { get; set; }
        public Nullable<int> Nr_zamowienia { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Miejscowość { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica_NrDomu { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Full_price { get; set; }
        public string Opis_zamowienia { get; set; }
    }
}
