//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesForSale
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Cena { get; set; }
        public string Podgatunek1 { get; set; }
        public string Podgatunek2 { get; set; }
        public string Podgatunek3 { get; set; }
        public string Podgatunek4 { get; set; }
        public string Tworca { get; set; }
        public Nullable<int> RokWydania { get; set; }
        public byte[] Image { get; set; }
        public string Gatunek { get; set; }
        public byte[] Zdj_tytulowe { get; set; }
        public string path_more { get; set; }
        public string path_wideo { get; set; }
    }
}
