//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaZakupow
    {
        public int Id { get; set; }
        public int Id_uzytkownika { get; set; }
        public string Nazwa_prod { get; set; }
        public string Cena { get; set; }
        public string Data_zakupu { get; set; }
    
        public virtual DaneKonta DaneKonta { get; set; }
    }
}
