//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kody
    {
        public int Id { get; set; }
        public string Nazwa_gry { get; set; }
        public string Kod_gry { get; set; }
    }
}
