#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "44A7A72816A6C1820FCFC609D100DE29D337EAE9E043CE4FDA0927C74BBE905B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AplikacjaClient;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AplikacjaClient {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 9 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid main;
        
        #line default
        #line hidden
        
        
        #line 77 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Exit;
        
        #line default
        #line hidden
        
        
        #line 82 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Minimize;
        
        #line default
        #line hidden
        
        
        #line 91 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid main1;
        
        #line default
        #line hidden
        
        
        #line 92 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Rejestracja;
        
        #line default
        #line hidden
        
        
        #line 159 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock labLogin;
        
        #line default
        #line hidden
        
        
        #line 160 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock takiNickJest;
        
        #line default
        #line hidden
        
        
        #line 163 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbLogin;
        
        #line default
        #line hidden
        
        
        #line 165 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock labPassword;
        
        #line default
        #line hidden
        
        
        #line 167 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbPassword;
        
        #line default
        #line hidden
        
        
        #line 173 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock labEmail;
        
        #line default
        #line hidden
        
        
        #line 174 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label takiEmailJest;
        
        #line default
        #line hidden
        
        
        #line 179 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbEmail;
        
        #line default
        #line hidden
        
        
        #line 181 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbAgrement;
        
        #line default
        #line hidden
        
        
        #line 183 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SignUpNow;
        
        #line default
        #line hidden
        
        
        #line 185 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button GotSignIn;
        
        #line default
        #line hidden
        
        
        #line 193 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label errorLogin;
        
        #line default
        #line hidden
        
        
        #line 198 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Logowanie;
        
        #line default
        #line hidden
        
        
        #line 259 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock labelemail;
        
        #line default
        #line hidden
        
        
        #line 260 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox emailusernameLogin;
        
        #line default
        #line hidden
        
        
        #line 261 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lpasswotd;
        
        #line default
        #line hidden
        
        
        #line 262 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox passwordLogin;
        
        #line default
        #line hidden
        
        
        #line 263 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid kontoihaslo;
        
        #line default
        #line hidden
        
        
        #line 275 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LogInNow;
        
        #line default
        #line hidden
        
        
        #line 277 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ClickToRegister;
        
        #line default
        #line hidden
        
        
        #line 283 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label bladLogowania;
        
        #line default
        #line hidden
        
        
        #line 284 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label brakUsera;
        
        #line default
        #line hidden
        
        
        #line 289 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PotwierdzenieRejestracji;
        
        #line default
        #line hidden
        
        
        #line 300 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btprzejdzdoLog;
        
        #line default
        #line hidden
        
        
        #line 302 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PotwierdzenieLogowania;
        
        #line default
        #line hidden
        
        
        #line 308 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Nick;
        
        #line default
        #line hidden
        
        
        #line 316 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid main2;
        
        #line default
        #line hidden
        
        
        #line 318 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup lzmiany;
        
        #line default
        #line hidden
        
        
        #line 320 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tc1;
        
        #line default
        #line hidden
        
        
        #line 322 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel lastUpdate;
        
        #line default
        #line hidden
        
        
        #line 345 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid listofChanges;
        
        #line default
        #line hidden
        
        
        #line 369 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup lkod;
        
        #line default
        #line hidden
        
        
        #line 370 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel st1;
        
        #line default
        #line hidden
        
        
        #line 372 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox kluczwpisywanie;
        
        #line default
        #line hidden
        
        
        #line 374 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock zlykod;
        
        #line default
        #line hidden
        
        
        #line 376 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button potwiedzenieklucza;
        
        #line default
        #line hidden
        
        
        #line 406 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton menupopup;
        
        #line default
        #line hidden
        
        
        #line 419 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup menukont;
        
        #line default
        #line hidden
        
        
        #line 447 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox filtrBiblioteki;
        
        #line default
        #line hidden
        
        
        #line 468 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridBiblioteka;
        
        #line default
        #line hidden
        
        
        #line 495 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel spsciezka;
        
        #line default
        #line hidden
        
        
        #line 505 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbsciezka;
        
        #line default
        #line hidden
        
        
        #line 506 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button potwiedzeniesciezki;
        
        #line default
        #line hidden
        
        
        #line 610 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid lftpanel;
        
        #line default
        #line hidden
        
        
        #line 633 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt1;
        
        #line default
        #line hidden
        
        
        #line 634 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt2;
        
        #line default
        #line hidden
        
        
        #line 635 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt3;
        
        #line default
        #line hidden
        
        
        #line 636 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt4;
        
        #line default
        #line hidden
        
        
        #line 637 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt5;
        
        #line default
        #line hidden
        
        
        #line 638 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt6;
        
        #line default
        #line hidden
        
        
        #line 639 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button leftbt7;
        
        #line default
        #line hidden
        
        
        #line 652 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridplacenie;
        
        #line default
        #line hidden
        
        
        #line 653 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock niepoprawnaKarta;
        
        #line default
        #line hidden
        
        
        #line 662 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid sposobplatVisa;
        
        #line default
        #line hidden
        
        
        #line 663 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel Visaplacenie;
        
        #line default
        #line hidden
        
        
        #line 665 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox imiePlacenie;
        
        #line default
        #line hidden
        
        
        #line 667 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox nazwiskoPlacenie;
        
        #line default
        #line hidden
        
        
        #line 669 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox nrkartyPlacenie;
        
        #line default
        #line hidden
        
        
        #line 671 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox kodPlacenie;
        
        #line default
        #line hidden
        
        
        #line 681 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridBasket;
        
        #line default
        #line hidden
        
        
        #line 693 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datagridKoszyk;
        
        #line default
        #line hidden
        
        
        #line 734 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label cenaMax;
        
        #line default
        #line hidden
        
        
        #line 741 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gProfile;
        
        #line default
        #line hidden
        
        
        #line 743 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel daneuzytkownika;
        
        #line default
        #line hidden
        
        
        #line 745 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox imieZmiana;
        
        #line default
        #line hidden
        
        
        #line 747 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox nazwiskoZmiana;
        
        #line default
        #line hidden
        
        
        #line 749 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NarodowoscZmiana;
        
        #line default
        #line hidden
        
        
        #line 751 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HobbySZmiana;
        
        #line default
        #line hidden
        
        
        #line 757 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel potwiedzenieZmianydanych;
        
        #line default
        #line hidden
        
        
        #line 761 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel potwiedzenieZmianyHasla;
        
        #line default
        #line hidden
        
        
        #line 767 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel spzmianahasla;
        
        #line default
        #line hidden
        
        
        #line 769 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox newPassword;
        
        #line default
        #line hidden
        
        
        #line 770 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock bladzmianyhasla;
        
        #line default
        #line hidden
        
        
        #line 775 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer scrollOrderhistory;
        
        #line default
        #line hidden
        
        
        #line 776 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid historiaZak;
        
        #line default
        #line hidden
        
        
        #line 805 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gryBibliotekaOkno;
        
        #line default
        #line hidden
        
        
        #line 824 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement video;
        
        #line default
        #line hidden
        
        
        #line 826 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btplay;
        
        #line default
        #line hidden
        
        
        #line 831 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btstop;
        
        #line default
        #line hidden
        
        
        #line 843 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider acctime;
        
        #line default
        #line hidden
        
        
        #line 859 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridpc;
        
        #line default
        #line hidden
        
        
        #line 877 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider Jakacena;
        
        #line default
        #line hidden
        
        
        #line 878 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textslidera;
        
        #line default
        #line hidden
        
        
        #line 888 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox rokmin;
        
        #line default
        #line hidden
        
        
        #line 889 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox rokmax;
        
        #line default
        #line hidden
        
        
        #line 895 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbkoop;
        
        #line default
        #line hidden
        
        
        #line 896 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbkmulti;
        
        #line default
        #line hidden
        
        
        #line 897 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbkopen;
        
        #line default
        #line hidden
        
        
        #line 898 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbkapo;
        
        #line default
        #line hidden
        
        
        #line 910 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames1;
        
        #line default
        #line hidden
        
        
        #line 912 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty1;
        
        #line default
        #line hidden
        
        
        #line 995 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames2;
        
        #line default
        #line hidden
        
        
        #line 997 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty2;
        
        #line default
        #line hidden
        
        
        #line 1080 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames3;
        
        #line default
        #line hidden
        
        
        #line 1082 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty3;
        
        #line default
        #line hidden
        
        
        #line 1166 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames4;
        
        #line default
        #line hidden
        
        
        #line 1168 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty4;
        
        #line default
        #line hidden
        
        
        #line 1251 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames5;
        
        #line default
        #line hidden
        
        
        #line 1253 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty5;
        
        #line default
        #line hidden
        
        
        #line 1336 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames6;
        
        #line default
        #line hidden
        
        
        #line 1338 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty6;
        
        #line default
        #line hidden
        
        
        #line 1421 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridgames7;
        
        #line default
        #line hidden
        
        
        #line 1423 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid gridProdukty7;
        
        #line default
        #line hidden
        
        
        #line 1506 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox wyborsortowania;
        
        #line default
        #line hidden
        
        
        #line 1525 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtfiltrowanie;
        
        #line default
        #line hidden
        
        
        #line 1531 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel potwiedzeniekodu;
        
        #line default
        #line hidden
        
        
        #line 1533 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock nazwaGrypotwiedzeniekodu;
        
        #line default
        #line hidden
        
        
        #line 1539 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid potwiedzenieplacenia;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AplikacjaClient;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "MainWindow.xaml"
            ((AplikacjaClient.MainWindow)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            
            #line 8 "MainWindow.xaml"
            ((AplikacjaClient.MainWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.main = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.Exit = ((System.Windows.Controls.Button)(target));
            
            #line 77 "MainWindow.xaml"
            this.Exit.Click += new System.Windows.RoutedEventHandler(this.Exit_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.Minimize = ((System.Windows.Controls.Button)(target));
            
            #line 82 "MainWindow.xaml"
            this.Minimize.Click += new System.Windows.RoutedEventHandler(this.Minimize_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.main1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.Rejestracja = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            
            #line 139 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 142 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_1);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 145 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_2);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 148 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_3);
            
            #line default
            #line hidden
            return;
            case 11:
            this.labLogin = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.takiNickJest = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.tbLogin = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.labPassword = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.tbPassword = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.labEmail = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.takiEmailJest = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.tbEmail = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.cbAgrement = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 20:
            this.SignUpNow = ((System.Windows.Controls.Button)(target));
            
            #line 183 "MainWindow.xaml"
            this.SignUpNow.Click += new System.Windows.RoutedEventHandler(this.SignUp_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.GotSignIn = ((System.Windows.Controls.Button)(target));
            
            #line 185 "MainWindow.xaml"
            this.GotSignIn.Click += new System.Windows.RoutedEventHandler(this.GotSignIn_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 190 "MainWindow.xaml"
            ((System.Windows.Controls.Label)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Label_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 23:
            this.errorLogin = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.Logowanie = ((System.Windows.Controls.Grid)(target));
            return;
            case 25:
            
            #line 245 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 248 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_1);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 251 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_2);
            
            #line default
            #line hidden
            return;
            case 28:
            
            #line 254 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_3);
            
            #line default
            #line hidden
            return;
            case 29:
            this.labelemail = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.emailusernameLogin = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.lpasswotd = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.passwordLogin = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 33:
            this.kontoihaslo = ((System.Windows.Controls.Grid)(target));
            return;
            case 34:
            this.LogInNow = ((System.Windows.Controls.Button)(target));
            
            #line 275 "MainWindow.xaml"
            this.LogInNow.Click += new System.Windows.RoutedEventHandler(this.LogInNow_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            this.ClickToRegister = ((System.Windows.Controls.Button)(target));
            
            #line 277 "MainWindow.xaml"
            this.ClickToRegister.Click += new System.Windows.RoutedEventHandler(this.ClickToRegister_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            
            #line 282 "MainWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Label_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 37:
            this.bladLogowania = ((System.Windows.Controls.Label)(target));
            return;
            case 38:
            this.brakUsera = ((System.Windows.Controls.Label)(target));
            return;
            case 39:
            this.PotwierdzenieRejestracji = ((System.Windows.Controls.Grid)(target));
            return;
            case 40:
            this.btprzejdzdoLog = ((System.Windows.Controls.Button)(target));
            
            #line 300 "MainWindow.xaml"
            this.btprzejdzdoLog.Click += new System.Windows.RoutedEventHandler(this.btprzejdzdoLog_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            this.PotwierdzenieLogowania = ((System.Windows.Controls.Grid)(target));
            return;
            case 42:
            this.Nick = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.main2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 44:
            this.lzmiany = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 45:
            this.tc1 = ((System.Windows.Controls.TabControl)(target));
            return;
            case 46:
            this.lastUpdate = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 47:
            this.listofChanges = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 48:
            this.lkod = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 49:
            this.st1 = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 50:
            this.kluczwpisywanie = ((System.Windows.Controls.TextBox)(target));
            return;
            case 51:
            this.zlykod = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.potwiedzenieklucza = ((System.Windows.Controls.Button)(target));
            
            #line 376 "MainWindow.xaml"
            this.potwiedzenieklucza.Click += new System.Windows.RoutedEventHandler(this.potwiedzenieklucza_Click);
            
            #line default
            #line hidden
            return;
            case 53:
            this.menupopup = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 54:
            this.menukont = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 55:
            
            #line 423 "MainWindow.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleButton_Click);
            
            #line default
            #line hidden
            return;
            case 56:
            
            #line 426 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_16);
            
            #line default
            #line hidden
            return;
            case 57:
            
            #line 428 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_15);
            
            #line default
            #line hidden
            return;
            case 58:
            
            #line 442 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_14);
            
            #line default
            #line hidden
            return;
            case 59:
            this.filtrBiblioteki = ((System.Windows.Controls.TextBox)(target));
            
            #line 447 "MainWindow.xaml"
            this.filtrBiblioteki.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.filtrBiblioteki_TextChanged);
            
            #line default
            #line hidden
            return;
            case 60:
            this.gridBiblioteka = ((System.Windows.Controls.DataGrid)(target));
            
            #line 468 "MainWindow.xaml"
            this.gridBiblioteka.SelectedCellsChanged += new System.Windows.Controls.SelectedCellsChangedEventHandler(this.gridBiblioteka_SelectedCellsChanged);
            
            #line default
            #line hidden
            
            #line 468 "MainWindow.xaml"
            this.gridBiblioteka.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.gridBiblioteka_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 62:
            this.spsciezka = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 63:
            
            #line 498 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_20);
            
            #line default
            #line hidden
            return;
            case 64:
            this.tbsciezka = ((System.Windows.Controls.TextBox)(target));
            return;
            case 65:
            this.potwiedzeniesciezki = ((System.Windows.Controls.Button)(target));
            
            #line 506 "MainWindow.xaml"
            this.potwiedzeniesciezki.Click += new System.Windows.RoutedEventHandler(this.potwiedzeniesciezki_Click);
            
            #line default
            #line hidden
            return;
            case 66:
            
            #line 564 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_8);
            
            #line default
            #line hidden
            return;
            case 67:
            
            #line 575 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 68:
            
            #line 582 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_9);
            
            #line default
            #line hidden
            return;
            case 69:
            
            #line 583 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_4);
            
            #line default
            #line hidden
            return;
            case 70:
            
            #line 584 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_3);
            
            #line default
            #line hidden
            return;
            case 71:
            
            #line 586 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_7);
            
            #line default
            #line hidden
            return;
            case 72:
            
            #line 596 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_2);
            
            #line default
            #line hidden
            return;
            case 73:
            
            #line 597 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_5);
            
            #line default
            #line hidden
            return;
            case 74:
            
            #line 598 "MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuItem_Click_6);
            
            #line default
            #line hidden
            return;
            case 75:
            
            #line 605 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_13);
            
            #line default
            #line hidden
            return;
            case 76:
            this.lftpanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 77:
            this.leftbt1 = ((System.Windows.Controls.Button)(target));
            
            #line 633 "MainWindow.xaml"
            this.leftbt1.Click += new System.Windows.RoutedEventHandler(this.leftbt1_Click);
            
            #line default
            #line hidden
            return;
            case 78:
            this.leftbt2 = ((System.Windows.Controls.Button)(target));
            
            #line 634 "MainWindow.xaml"
            this.leftbt2.Click += new System.Windows.RoutedEventHandler(this.leftbt2_Click);
            
            #line default
            #line hidden
            return;
            case 79:
            this.leftbt3 = ((System.Windows.Controls.Button)(target));
            
            #line 635 "MainWindow.xaml"
            this.leftbt3.Click += new System.Windows.RoutedEventHandler(this.leftbt3_Click);
            
            #line default
            #line hidden
            return;
            case 80:
            this.leftbt4 = ((System.Windows.Controls.Button)(target));
            
            #line 636 "MainWindow.xaml"
            this.leftbt4.Click += new System.Windows.RoutedEventHandler(this.leftbt4_Click);
            
            #line default
            #line hidden
            return;
            case 81:
            this.leftbt5 = ((System.Windows.Controls.Button)(target));
            
            #line 637 "MainWindow.xaml"
            this.leftbt5.Click += new System.Windows.RoutedEventHandler(this.leftbt5_Click);
            
            #line default
            #line hidden
            return;
            case 82:
            this.leftbt6 = ((System.Windows.Controls.Button)(target));
            
            #line 638 "MainWindow.xaml"
            this.leftbt6.Click += new System.Windows.RoutedEventHandler(this.leftbt6_Click);
            
            #line default
            #line hidden
            return;
            case 83:
            this.leftbt7 = ((System.Windows.Controls.Button)(target));
            
            #line 639 "MainWindow.xaml"
            this.leftbt7.Click += new System.Windows.RoutedEventHandler(this.leftbt7_Click);
            
            #line default
            #line hidden
            return;
            case 84:
            this.gridplacenie = ((System.Windows.Controls.Grid)(target));
            return;
            case 85:
            this.niepoprawnaKarta = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 86:
            
            #line 654 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_18);
            
            #line default
            #line hidden
            return;
            case 87:
            
            #line 655 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_11);
            
            #line default
            #line hidden
            return;
            case 88:
            this.sposobplatVisa = ((System.Windows.Controls.Grid)(target));
            return;
            case 89:
            this.Visaplacenie = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 90:
            this.imiePlacenie = ((System.Windows.Controls.TextBox)(target));
            return;
            case 91:
            this.nazwiskoPlacenie = ((System.Windows.Controls.TextBox)(target));
            return;
            case 92:
            this.nrkartyPlacenie = ((System.Windows.Controls.TextBox)(target));
            return;
            case 93:
            this.kodPlacenie = ((System.Windows.Controls.TextBox)(target));
            return;
            case 94:
            this.gridBasket = ((System.Windows.Controls.Grid)(target));
            return;
            case 95:
            
            #line 682 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_10);
            
            #line default
            #line hidden
            return;
            case 96:
            
            #line 683 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_9);
            
            #line default
            #line hidden
            return;
            case 97:
            this.datagridKoszyk = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 99:
            this.cenaMax = ((System.Windows.Controls.Label)(target));
            return;
            case 100:
            this.gProfile = ((System.Windows.Controls.Grid)(target));
            return;
            case 101:
            this.daneuzytkownika = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 102:
            this.imieZmiana = ((System.Windows.Controls.TextBox)(target));
            return;
            case 103:
            this.nazwiskoZmiana = ((System.Windows.Controls.TextBox)(target));
            return;
            case 104:
            this.NarodowoscZmiana = ((System.Windows.Controls.TextBox)(target));
            return;
            case 105:
            this.HobbySZmiana = ((System.Windows.Controls.TextBox)(target));
            return;
            case 106:
            
            #line 753 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_26);
            
            #line default
            #line hidden
            return;
            case 107:
            this.potwiedzenieZmianydanych = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 108:
            
            #line 759 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_29);
            
            #line default
            #line hidden
            return;
            case 109:
            this.potwiedzenieZmianyHasla = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 110:
            
            #line 763 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_30);
            
            #line default
            #line hidden
            return;
            case 111:
            this.spzmianahasla = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 112:
            this.newPassword = ((System.Windows.Controls.TextBox)(target));
            return;
            case 113:
            this.bladzmianyhasla = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 114:
            
            #line 771 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_24);
            
            #line default
            #line hidden
            return;
            case 115:
            this.scrollOrderhistory = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 116:
            this.historiaZak = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 117:
            
            #line 800 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_22);
            
            #line default
            #line hidden
            return;
            case 118:
            
            #line 801 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_23);
            
            #line default
            #line hidden
            return;
            case 119:
            
            #line 802 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_25);
            
            #line default
            #line hidden
            return;
            case 120:
            this.gryBibliotekaOkno = ((System.Windows.Controls.Grid)(target));
            return;
            case 121:
            
            #line 810 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_28);
            
            #line default
            #line hidden
            return;
            case 122:
            
            #line 820 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_21);
            
            #line default
            #line hidden
            return;
            case 123:
            this.video = ((System.Windows.Controls.MediaElement)(target));
            
            #line 824 "MainWindow.xaml"
            this.video.MediaOpened += new System.Windows.RoutedEventHandler(this.video_MediaOpened);
            
            #line default
            #line hidden
            return;
            case 124:
            this.btplay = ((System.Windows.Controls.Button)(target));
            
            #line 826 "MainWindow.xaml"
            this.btplay.Click += new System.Windows.RoutedEventHandler(this.VideoPlaY);
            
            #line default
            #line hidden
            return;
            case 125:
            this.btstop = ((System.Windows.Controls.Button)(target));
            
            #line 831 "MainWindow.xaml"
            this.btstop.Click += new System.Windows.RoutedEventHandler(this.VideoPause);
            
            #line default
            #line hidden
            return;
            case 126:
            
            #line 836 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.VideoStop);
            
            #line default
            #line hidden
            return;
            case 127:
            this.acctime = ((System.Windows.Controls.Slider)(target));
            
            #line 843 "MainWindow.xaml"
            this.acctime.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.acctime_ValueChanged);
            
            #line default
            #line hidden
            
            #line 843 "MainWindow.xaml"
            this.acctime.AddHandler(System.Windows.Controls.Primitives.Thumb.DragStartedEvent, new System.Windows.Controls.Primitives.DragStartedEventHandler(this.acctime_DragStarted));
            
            #line default
            #line hidden
            
            #line 843 "MainWindow.xaml"
            this.acctime.AddHandler(System.Windows.Controls.Primitives.Thumb.DragCompletedEvent, new System.Windows.Controls.Primitives.DragCompletedEventHandler(this.acctime_DragCompleted));
            
            #line default
            #line hidden
            return;
            case 128:
            this.gridpc = ((System.Windows.Controls.Grid)(target));
            return;
            case 129:
            
            #line 874 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_7);
            
            #line default
            #line hidden
            return;
            case 130:
            this.Jakacena = ((System.Windows.Controls.Slider)(target));
            
            #line 877 "MainWindow.xaml"
            this.Jakacena.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.Jakacena_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 131:
            this.textslidera = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 132:
            this.rokmin = ((System.Windows.Controls.TextBox)(target));
            return;
            case 133:
            this.rokmax = ((System.Windows.Controls.TextBox)(target));
            return;
            case 134:
            this.cbkoop = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 135:
            this.cbkmulti = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 136:
            this.cbkopen = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 137:
            this.cbkapo = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 138:
            this.gridgames1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 139:
            this.gridProdukty1 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 141:
            this.gridgames2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 142:
            this.gridProdukty2 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 144:
            this.gridgames3 = ((System.Windows.Controls.Grid)(target));
            return;
            case 145:
            this.gridProdukty3 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 147:
            this.gridgames4 = ((System.Windows.Controls.Grid)(target));
            return;
            case 148:
            this.gridProdukty4 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 150:
            this.gridgames5 = ((System.Windows.Controls.Grid)(target));
            return;
            case 151:
            this.gridProdukty5 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 153:
            this.gridgames6 = ((System.Windows.Controls.Grid)(target));
            return;
            case 154:
            this.gridProdukty6 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 156:
            this.gridgames7 = ((System.Windows.Controls.Grid)(target));
            return;
            case 157:
            this.gridProdukty7 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 159:
            this.wyborsortowania = ((System.Windows.Controls.ComboBox)(target));
            
            #line 1506 "MainWindow.xaml"
            this.wyborsortowania.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.wyborsortowania_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 160:
            this.txtfiltrowanie = ((System.Windows.Controls.TextBox)(target));
            
            #line 1525 "MainWindow.xaml"
            this.txtfiltrowanie.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.txtfiltrowanie_TextChanged);
            
            #line default
            #line hidden
            return;
            case 161:
            
            #line 1526 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_4);
            
            #line default
            #line hidden
            return;
            case 162:
            this.potwiedzeniekodu = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 163:
            this.nazwaGrypotwiedzeniekodu = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 164:
            
            #line 1535 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_17);
            
            #line default
            #line hidden
            return;
            case 165:
            this.potwiedzenieplacenia = ((System.Windows.Controls.Grid)(target));
            return;
            case 166:
            
            #line 1541 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_12);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 61:
            
            #line 481 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_19);
            
            #line default
            #line hidden
            break;
            case 98:
            
            #line 718 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click_8);
            
            #line default
            #line hidden
            break;
            case 140:
            
            #line 984 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz1_Click);
            
            #line default
            #line hidden
            break;
            case 143:
            
            #line 1069 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz2_Click);
            
            #line default
            #line hidden
            break;
            case 146:
            
            #line 1154 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz3_Click);
            
            #line default
            #line hidden
            break;
            case 149:
            
            #line 1240 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz4_Click);
            
            #line default
            #line hidden
            break;
            case 152:
            
            #line 1325 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz5_Click);
            
            #line default
            #line hidden
            break;
            case 155:
            
            #line 1410 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz6_Click);
            
            #line default
            #line hidden
            break;
            case 158:
            
            #line 1495 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btndodajDoKosz7_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

